version: '3.4'

services:
  efcoreweb:
    image: ${DOCKER_REGISTRY-}efcoreweb
    build:
      context: .
      dockerfile: src/EFCoreWeb/Dockerfile

  ms_sql:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MyP4ssword%"
      ACCEPT_EULA: "Y"
